version: '3'
services:
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1881:1880"
    volumes:
      - ./data:/data
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  python-script:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - mqtt-broker
